// scripts/build.mjs — bundlea src/wrapper.mjs → dist/box-worker.mjs con esbuild.
//
// El bundle:
//   - target esnext (Workers son V8 reciente, soporta syntax moderna)
//   - format esm (WFP module format — workers/scripts.update requiere
//     metadata.main_module + archivo .mjs, ver Cloudflare docs)
//   - external = nada — todo se bundlea en un único archivo
//   - minify (reducir tamaño para upload rápido)
//   - platform neutral (Node-style imports, no specific platform flag)
//
// nanoid (usado por @htmlbox/shared/src/id.js) requiere node:crypto, que
// no existe en Workers isolate. El per-box script NO necesita nanoid (solo lo
// necesita el control-plane para generar boxIds/shareIds), así que lo
// stubamos a un objeto vacío. Si en el futuro @htmlbox/shared agrega
// algo que el per-box script use y rompe, esto va a explotar y nos
// vamos a enterar rápido.
//
// Después del build, copiamos el bundle a packages/control-plane/src/ui-partials/
// (como .txt) para que el control-plane Worker pueda importarlo vía wrangler
// Text rule. Sin este sync, wfpDeployer no podría leer el bundle (Workers
// no tienen node:fs).

import { build } from 'esbuild'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

await build({
  entryPoints: [path.join(root, 'src/wrapper.mjs')],
  outfile: path.join(root, 'dist/box-worker.mjs'),
  bundle: true,
  format: 'esm',
  target: 'esnext',
  platform: 'neutral',
  minify: true,
  sourcemap: false,
  banner: { js: '// htmlbox runtime-box-worker (built ' + new Date().toISOString() + ')' },
  metafile: false,
  logLevel: 'info',
  alias: {
    nanoid: path.join(root, 'scripts/nanoid-stub.mjs'),
  },
})

// Sync al control-plane — escribimos un módulo JS que exporta el bundle
// como string. Esto permite:
//   1. Node lo importa como un módulo regular (los tests del control-plane
//      pueden leerlo sin necesidad de wrangler Text rule).
//   2. wrangler no necesita rule especial — es un .js cualquiera.
//   3. JSON.stringify se encarga del escape correcto de backticks, ${,
//      newlines, etc.
//
// Naming: `box-worker.mjs.js` — el primer .mjs es decorativo (hace
// evidente que el contenido es un módulo de Worker), el .js final es
// lo que Node/wrangler reconocen como módulo JS.
const cpTarget = path.resolve(root, '..', 'control-plane', 'src', 'ui-partials', 'box-worker.mjs.js')
await fs.mkdir(path.dirname(cpTarget), { recursive: true })
const bundleSource = await fs.readFile(path.join(root, 'dist/box-worker.mjs'), 'utf8')
// JSON.stringify escapa backslashes, backticks, ${, y caracteres de control.
const encoded = JSON.stringify(bundleSource)
const wrapper = `// Auto-generated by packages/runtime-box-worker/scripts/build.mjs.\n// Do NOT edit by hand — re-run \`npm run build -w @htmlbox/runtime-box-worker\` instead.\nexport default ${encoded};\n`
await fs.writeFile(cpTarget, wrapper, 'utf8')

console.log(`✓ built dist/box-worker.mjs`)
console.log(`✓ synced to ${path.relative(root, cpTarget)}`)

