#!/usr/bin/env node
// scripts/build.mjs — bundlea box-template/worker.js → dist/box-worker.mjs.
//
// Qué hace:
//   1. Lee box-template/editors/app-studio.html.txt y editor-vanilla.html.txt.
//   2. Reemplaza los placeholders __APP_STUDIO_HTML_PLACEHOLDER__ y
//      __EDITOR_VANILLA_HTML_PLACEHOLDER__ en box-template/worker.js por
//      strings JSON-escaped del contenido de cada editor.
//   3. Bundlea con esbuild → dist/box-worker.mjs (formato ESM, target esnext,
//      minify — Workers for Platforms acepta hasta 1 MB).
//   4. Genera dist/box-worker.mjs.js (un wrapper que exporta el bundle como
//      string) para que el launcher-worker lo importe como módulo regular
//      y lo suba a WFP vía wfpDeployer (Workers no tienen node:fs).
//
// Patrón idéntico a packages/runtime-box-worker/scripts/build.mjs — lo
// duplicamos intencionalmente porque sivostudio no comparte código con
// control-plane/runtime (aislamiento total por diseño del experimento).

import { build } from 'esbuild'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const TEMPLATE_PATH = path.join(root, 'box-template', 'worker.js')
const APP_STUDIO_PATH = path.join(root, 'box-template', 'editors', 'app-studio.html.txt')
const EDITOR_VANILLA_PATH = path.join(root, 'box-template', 'editors', 'editor-vanilla.html.txt')

const OUT_DIR = path.join(root, 'dist')
const BUNDLE_PATH = path.join(OUT_DIR, 'box-worker.mjs')
const STRING_WRAPPER_PATH = path.join(OUT_DIR, 'box-worker.mjs.js')

// 1) Leer fuentes.
const [template, appStudioHtml, editorVanillaHtml] = await Promise.all([
  fs.readFile(TEMPLATE_PATH, 'utf8'),
  fs.readFile(APP_STUDIO_PATH, 'utf8'),
  fs.readFile(EDITOR_VANILLA_PATH, 'utf8'),
])

// 2) Reemplazar placeholders por template literals con el contenido.
//
//    ¿Por qué template literals (backticks) y no JSON.stringify?
//    JSON.stringify devuelve `"<html>..."` (envuelto en comillas dobles).
//    Si lo meto directo en el código fuente queda:
//        const X = '"<html>..."'
//    Que es JS válido PERO produce: string vacío + identificador `"<html>..."`
//    sin cerrar. Por eso falla esbuild con "Expected ; but found help".
//
//    Con template literals queda:
//        const X = `<html>...`
//    Que sí es válido — los backticks encierran todo el contenido, sin
//    importar comillas simples/dobles internas.
//
//    Escapamos manualmente lo que rompería un template literal:
//      `  →  \`     (cierre del template)
//      $  →  \$     (inicio de ${...} interpolation)
//      \  →  \\     (escape de backslash)
//    El HTML de App Studio no debería contener ninguno de los tres, pero
//    el escape defensivo cuesta nada y previene foot-guns.
function escapeForTemplateLiteral(str) {
  return str
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('$', '\\$')
}

if (!template.includes("'__APP_STUDIO_HTML_PLACEHOLDER__'")) {
  throw new Error(
    `Placeholder '__APP_STUDIO_HTML_PLACEHOLDER__' (con comillas) no encontrado en ${TEMPLATE_PATH}. ` +
    'El template debe tener la forma: const X = \'__PLACEHOLDER__\'\n' +
    '¿Renombraste la constante sin actualizar este build?',
  )
}
if (!template.includes("'__EDITOR_VANILLA_HTML_PLACEHOLDER__'")) {
  throw new Error(
    `Placeholder '__EDITOR_VANILLA_HTML_PLACEHOLDER__' (con comillas) no encontrado en ${TEMPLATE_PATH}.`,
  )
}

// Reemplazamos el LITERAL ENTERO (placeholder + comillas exteriores) por el
// template literal con backticks. Sin esto, las comillas simples del template
// original quedarían al lado del backtick: const X = '`<html>...` → inválido.
const inlined = template
  .replace("'__APP_STUDIO_HTML_PLACEHOLDER__'", '`' + escapeForTemplateLiteral(appStudioHtml) + '`')
  .replace("'__EDITOR_VANILLA_HTML_PLACEHOLDER__'", '`' + escapeForTemplateLiteral(editorVanillaHtml) + '`')

const inlinedPath = path.join(OUT_DIR, 'box-worker.inlined.mjs')
await fs.mkdir(OUT_DIR, { recursive: true })
await fs.writeFile(inlinedPath, inlined, 'utf8')

// 3) Bundle con esbuild.
await build({
  entryPoints: [inlinedPath],
  outfile: BUNDLE_PATH,
  bundle: true,
  format: 'esm',
  target: 'esnext',
  platform: 'neutral',
  minify: true,
  sourcemap: false,
  banner: { js: '// htmlbox sivostudio box-template (built ' + new Date().toISOString() + ')' },
  metafile: false,
  logLevel: 'info',
})

// 4) Wrapper que exporta el bundle como string — para que wfpDeployer lo
//    importe como módulo regular (sin wrangler Text rule). Patrón copiado
//    de runtime-box-worker/scripts/build.mjs.
const bundleSource = await fs.readFile(BUNDLE_PATH, 'utf8')
const encoded = JSON.stringify(bundleSource)
const wrapper =
  `// Auto-generated by packages/sivostudio/scripts/build.mjs.\n` +
  `// Do NOT edit by hand — re-run \`npm run build -w @htmlbox/sivostudio\` instead.\n` +
  `export default ${encoded};\n`
await fs.writeFile(STRING_WRAPPER_PATH, wrapper, 'utf8')

const bundleSizeKb = (Buffer.byteLength(bundleSource, 'utf8') / 1024).toFixed(1)
console.log(`✓ built ${path.relative(root, BUNDLE_PATH)} (${bundleSizeKb} KB)`)
console.log(`✓ wrapper ${path.relative(root, STRING_WRAPPER_PATH)}`)
console.log(`✓ inlined intermediate cleaned: ${path.relative(root, inlinedPath)}`)

// Limpiar el intermediate inlined — solo lo necesitamos como entry para
// esbuild, no como artefacto.
await fs.unlink(inlinedPath)
